import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const REQUIRED_ENV_KEYS = [
  'EXPO_PUBLIC_FIREBASE_API_KEY',
  'EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'EXPO_PUBLIC_FIREBASE_PROJECT_ID',
  'EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET',
  'EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'EXPO_PUBLIC_FIREBASE_APP_ID',
];

function loadEnvFile() {
  const envPath = resolve(process.cwd(), '.env');

  try {
    const content = readFileSync(envPath, 'utf8');
    const env = {};

    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }

      const separatorIndex = trimmed.indexOf('=');
      if (separatorIndex === -1) {
        continue;
      }

      const key = trimmed.slice(0, separatorIndex).trim();
      const value = trimmed.slice(separatorIndex + 1).trim();
      env[key] = value;
    }

    return { env, envPath };
  } catch {
    return { env: null, envPath };
  }
}

function main() {
  const { env, envPath } = loadEnvFile();

  if (!env) {
    console.error(`Could not read ${envPath}. Copy .env.example to .env first.`);
    process.exit(1);
  }

  const missing = REQUIRED_ENV_KEYS.filter((key) => !env[key]);
  if (missing.length > 0) {
    console.error('Missing Firebase values in .env:');
    missing.forEach((key) => console.error(`  - ${key}`));
    process.exit(1);
  }

  const firebaseConfig = {
    apiKey: env.EXPO_PUBLIC_FIREBASE_API_KEY,
    authDomain: env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: env.EXPO_PUBLIC_FIREBASE_APP_ID,
  };

  const hostingPublicDir = resolve(process.cwd(), 'hosting-public');
  mkdirSync(hostingPublicDir, { recursive: true });

  const configPath = resolve(hostingPublicDir, 'firebase-config.js');
  writeFileSync(
    configPath,
    `// Generated by scripts/build-hosting.mjs — do not edit.\nwindow.FIREBASE_CONFIG = ${JSON.stringify(firebaseConfig, null, 2)};\n`,
    'utf8',
  );

  const firebasercPath = resolve(process.cwd(), '.firebaserc');
  writeFileSync(
    firebasercPath,
    `${JSON.stringify({ projects: { default: firebaseConfig.projectId } }, null, 2)}\n`,
    'utf8',
  );

  console.log(`Built hosting config for project "${firebaseConfig.projectId}".`);
  console.log(`  ${configPath}`);
  console.log(`  ${firebasercPath}`);
}

main();
